version: "3"
services:
  app:
    build: .
    image: gkoy/komodo
    container_name: komodo-app
    ports:
      - published: 80
        target: 8000
    links:
      - redis
    env_file:
      - server/.env

  redis:
    image: redis:alpine
    container_name: komodo-redis
    expose:
      - 6379
